name: GCC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gcc:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 12, 13 ]
        config: [ Debug, Release ]

    steps:
      - uses: actions/checkout@master

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install compiler
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt install gcc-${{matrix.version}} g++-${{matrix.version}}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{matrix.version}} 110 --slave /usr/bin/g++ g++ /usr/bin/g++-${{matrix.version}} --slave /usr/bin/gcov gcov /usr/bin/gcov-${{matrix.version}}
          g++ --version

      - name: Create build environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake -G Ninja $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.config}}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config ${{matrix.config}}

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest --build-config ${{matrix.config}} --rerun-failed --output-on-failure

